2019-03-25 23:40:09,449 INFO: Microblog startup [in /home/jurgeon/Desktop/microblog12/app/__init__.py:49]
2019-03-25 23:40:13,916 INFO: Microblog startup [in /home/jurgeon/Desktop/microblog12/app/__init__.py:49]
2019-03-25 23:40:18,439 INFO: Microblog startup [in /home/jurgeon/Desktop/microblog12/app/__init__.py:49]
2019-03-25 23:40:25,367 INFO: Microblog startup [in /home/jurgeon/Desktop/microblog12/app/__init__.py:49]
2019-03-25 23:40:32,357 INFO: Microblog startup [in /home/jurgeon/Desktop/microblog12/app/__init__.py:49]
2019-03-25 23:45:06,091 INFO: Microblog startup [in /home/jurgeon/Desktop/microblog12/app/__init__.py:49]
2019-03-25 23:47:51,993 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-25 23:49:24,473 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-25 23:49:24,992 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-26 00:25:45,220 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-26 00:25:45,766 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-26 00:26:37,132 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-26 00:27:27,679 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-26 00:31:13,482 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:57]
2019-03-26 00:31:14,037 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:57]
2019-03-26 00:32:48,990 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:57]
2019-03-26 00:33:19,574 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:58]
2019-03-26 00:33:20,106 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:58]
2019-03-26 00:35:29,424 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:58]
2019-03-26 00:37:41,830 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:58]
2019-03-26 00:39:28,338 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:58]
2019-03-26 00:39:28,846 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:58]
2019-03-26 00:40:05,945 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-26 00:40:11,595 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-26 00:40:12,123 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-26 00:40:30,060 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-26 00:40:33,736 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-28 09:11:04,799 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:49]
2019-03-28 10:23:25,882 INFO: Microblog startup [in /home/jurgeon/Dropbox/dev/flask_projects/microblog/app/__init__.py:50]
2019-03-28 10:23:30,802 ERROR: Exception on /edit_profile [POST] [in /home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jurgeon/Dropbox/dev/flask_projects/microblog/app/routes.py", line 146, in edit_profile
    if form.validate_on_submit():
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/home/jurgeon/Dropbox/dev/flask_projects/microblog/app/forms.py", line 56, in validate_username
    if username.data != current_user.username:
NameError: name 'current_user' is not defined
2019-03-28 10:24:52,665 ERROR: Exception on /edit_profile [POST] [in /home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jurgeon/Dropbox/dev/flask_projects/microblog/app/routes.py", line 146, in edit_profile
    if form.validate_on_submit():
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/home/jurgeon/Dropbox/dev/flask_projects/microblog/app/forms.py", line 56, in validate_username
    if username.data != self.original_username:
NameError: name 'current_user' is not defined
2019-03-28 10:25:02,156 ERROR: Exception on /edit_profile [POST] [in /home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jurgeon/Dropbox/dev/flask_projects/microblog/app/routes.py", line 146, in edit_profile
    if form.validate_on_submit():
  File "/home/jurgeon/.local/lib/python3.6/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/jurgeon/.local/lib/python3.6/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/home/jurgeon/Dropbox/dev/flask_projects/microblog/app/forms.py", line 56, in validate_username
    if username.data != self.original_username:
NameError: name 'current_user' is not defined
